const MSG = {
  VALIDATION_ERR: 'Validate error',
  EMAIL_IS_REQUIRED: 'Email là bắt buộc',
  EMAIL_MUST_BE_STRING: 'Email phải là dạng chuỗi ký tự',
  EMAIL_LENGTH: 'Email có độ dài từ 5 đến 160 ký tự',
  EMAIL_INVALID: 'Email chưa đúng định dạng',
  PASSWORD_IS_REQUIRED: 'Mật khẩu là bắt buộc',
  PASSWORD_LENGTH: 'Mật khẩu có độ dài từ 6 đến 160 ký tự',
  PASSWORD_IS_NOT_STRONG: 'Mật khẩu chưa đủ bảo mật',
  EMAIL_OR_PASSWORD_INCORRECT: 'Email hoặc mật khẩu chưa chính xác',
  LOGIN_SUCCESS: 'Đăng nhập tài khoản thành công',
  LOGOUT_SUCCESS: 'Đăng xuất tài khoản thành công',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token là bắt buộc',
  TOKEN_NOT_FOUND: 'Không tìm thấy token',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token là bắt buộc',
  CREATED_USER_SUCCESS: 'Tạo tài khoản thành công',
  VERIFY_USER_INVALID: 'Tài khoản chưa được xác thực',
  NO_PERMISSION_CREATE_USER: 'Không đủ quyền để tạo user',
  EMAIL_ALREADY_EXISTS: 'Email đã tồn tại',
  ID_IS_REQUIRED: 'Id là bắt buộc',
  ID_MUST_BE_NUMBER: 'Id phải là dạng số',
  USER_NOT_FOUND: 'Không tìm thấy user',
  UPDATED_USER_SUCCESS: 'Cập nhật user thành công',
  FULLNAME_MUST_BE_STRING: 'Họ và tên phải là dạng chuỗi',
  NAME_CUSTOMER_MUST_BE_STRING: 'Tên dịch vụ phải là dạng chuỗi',
  FULLNAME_LENGTH: 'Họ và tên có độ dài từ 4 đến 160 ký tự',
  NAME_CUSTOMER_LENGTH: 'Tên dịch vụ có độ dài từ 3 đến 160 ký tự',
  DATE_OF_BIRTH_ISO8601: 'Ngày tháng năm sinh phải là dạng ISO8601',
  TIME_START_ISO8601: 'Thời gian bắt đầu phải là dạng ISO8601',
  TIME_END_ISO8601: 'Thời gian kết thúc phải là dạng ISO8601',
  ASSIGN_AT_ISO8601: 'Assign at phải là ISO 8601',
  AVATAR_MUST_BE_STRING: 'Ảnh đại diện phải là dạng chuỗi',
  AVATAR_LENGTH: 'Ảnh đại diện có độ dài từ 6 đến 255 ký tự',
  ATTACHMENT_LENGTH: 'File đính kèm có độ dài từ 6 đến 255 ký tự',
  ADDRESS_MUST_BE_STRING: 'Địa chỉ phải là dạng chuỗi',
  ADDRESS_LENGTH: 'Địa chỉ có độ dài từ 6 đến 160 ký tự',
  PHONE_MUST_BE_STRING: 'Số điện thoại phải là dạng chuỗi',
  PHONE_LENGTH: 'Số điện có độ dài 10 ký tự',
  CODE_MUST_BE_STRING: 'Mã nhân viên phải là dạng chuỗi',
  CODE_LENGTH: 'Mã nhân viên có độ dài 6 ký tự',
  ROLE_INVALID: 'Role chưa đúng định dạng',
  OLD_PASSWORD_INCORRECT: 'Mật khẩu cũ không chính xác',
  CHANGED_PASSWORD_SUCCESSS: 'Thay đổi mật khẩu thành công',
  NOT_FOUND: 'Not Found',
  UPLOAD_AVATAR_SUCCESSFULLY: 'Upload avatar thành công',
  GET_LIST_USER_SUCCESS: 'Lấy danh sách user thành công',
  GET_DETAIL_USER_SUCCESS: 'Lấy user thành công',
  REFRESH_TOKEN_SUCCESS: 'Refresh token thành công',
  USER_VERIFY_STATUS_INVALID: 'Verify status invalid',
  GET_ME_SUCCESS: 'Lấy thông tin profile user thành công',
  CREATED_CUSTOMER_SUCCESS: 'Thêm mới khách hàng thành công',
  CUSTOMER_TYPE_INVALID: 'Type khách hàng không hợp lệ',
  NAME_CUSTOMER_ALREADY_EXISTS: 'Tên khách hàng đã tồn tại',
  CUSTOMER_NOT_FOUND: 'Không tìm thấy khách hàng',
  TAX_CODE_IS_REQUIRED: 'Mã số thuế là bắt buộc',
  TAX_CODE_LENGTH: 'Mã số thuế cho phép tối thiểu 10 và tối đa 13 ký tự',
  WEBSITE_MUST_BE_STRING: 'Website nhập vào phải là dạng chuỗi',
  WEBSITE_LENGTH: 'Website cho phép tối thiểu 1 và tối đa 50 ký tự',
  SURROGATE_MUST_BE_STRING: 'Người đại diện nhập vào phải là dạng chuỗi',
  SURROGATE_MUST_LENGTH: 'Người đại diện nhập vào có độ dài từ 4 đến 160 ký tự',
  ATTACHMENT_MUST_BE_STRING: 'File đính kèm phải là dạng chuỗi',
  NOTE_MAX_LENGTH: 'Ghi chú không được phép vượt quá 2000 ký tự',
  CONTENT_MAX_LENGTH: 'Nội dung không được phép vượt quá 2000 ký tự',
  UPDATED_CUSTOMER_SUCCESS: 'Cập nhật thông tin khách hàng thành công',
  IS_CUSTOMER_COMPANY: 'Khách hàng phải là khách hàng doanh nghiệp',
  IS_CUSTOMER_PERSONAL: 'Khách hàng phải là khách hàng cá nhân',
  CUSTOMER_GENDER_INVALID: 'Giới tính khách hàng chưa phù hợp',
  LIMIT_LENGHT: 'Giới hạn phân trang có giá trị phải lớn 1 và bé hơn 100',
  PAGE_INVALID: 'Số trang phải có giá trị lớn hơn 1 hoặc bằng 1',
  UPLOAD_FILE_SUCCESSFULLY: 'Upload file đính kèm thành công',
  CUSTOMER_STATUS_INVALID: 'Trạng thái khách hàng phải là Active hoặc Deactivated',
  CUSTOMER_VERIFY_INVALID: 'Xác thực khách hàng phải là Unverified hoặc Verified',
  GET_LIST_CUSTOMER_SUCCESS: 'Lấy danh sách khách hàng thành công',
  CCCD_IS_REQUIRED: 'Căn cước công dân là bắt buộc',
  CCCD_LENGTH: 'Độ dài căn cước công dân là 12 chuỗi ký tự',
  ATTACHMENTS_IS_REQUIRED: 'Attachments là bắt buộc',
  ATTACHMENTS_MUST_BE_ARRAY: 'Attachments phải là mảng',
  ATTACHMENT_ITEM_MUST_BE_ARRAY_STRING: 'Attachments item phải là dạng chuỗi',
  GET_CUSTOMER_SUCCESS: 'Lấy thông tin khách hàng thành công',
  CUSTOMER_IS_VERIFIED: 'Khách hàng đã được xác thực trước đó',
  RESET_PASSWORD_SUCCESS: 'Làm mới mật khẩu thành công',
  NAME_PERFORMANCE_MUST_BE_STRING: 'Tiêu đề hiệu quả công việc phải là dạng chuỗi',
  NAME_PERFORMANCE_LENGTH: 'Tiêu đề hiệu quả công việc có độ dài từ 3 đến 160 ký tự',
  CREATOR_ID_IS_REQUIRED: 'creator_id là bắt buộc',
  CUSTOMER_ID_IS_REQUIRED: 'customer_id là bắt buộc',
  PERFORMANCE_STATUS_INVALID: 'Trạng thái hiệu quả công việc không hợp lệ',
  OPERATING_COST_MUST_BE_NUMBER_FROM_0_TO_100: 'Chi phí vận hành phải là số từ 0 đến 100',
  OPERATING_COST_IS_REQUIRED: 'Chi phí vận hành là bắt buộc',
  CUSTOMER_CARE_COST_IS_REQUIRED: 'Chi phí CSKH là bắt buộc',
  CUSTOMER_CARE_COST_MUST_BE_NUMBER_FROM_0_TO_100: 'Chi phí CSKH phải là số từ 0 đến 100',
  COMMISSION_COST_IS_REQUIRED: 'Chi phí hoa hồng là bắt buộc',
  COMMISSION_COST_MUST_BE_NUMBER_FROM_0_TO_100: 'Chi phí hoa hồng phải là số từ 0 đến 100',
  DIPLOMATIC_COST_IS_REQUIRED: 'Chi phí ngoại giao là bắt buộc',
  DIPLOMATIC_COST_MUST_BE_NUMBER_FROM_0_TO_100: 'Chi phí ngoại giao phải là số từ 0 đến 100',
  RESERVE_COST_IS_REQUIRED: 'Chi phí dự phòng là bắt buộc',
  RESERVE_COST_MUST_BE_NUMBER_FROM_0_TO_100: 'Chi phí dự phòng phải là số từ 0 đến 100',
  CUSTOMER_COST_IS_REQUIRED: 'Chi phí khách hàng là bắt buộc',
  CUSTOMER_COST_MUST_BE_NUMBER_FROM_0_TO_100: 'Chi phí khách hàng phải là số từ 0 đến 100',
  CREATE_PERFORMANCE_SUCCESS: 'Thêm mới hiệu quả công việc thành công',
  ID_PERFORMANCE_IS_REQUIRED: 'Id hiệu quả công việc là bắt buộc',
  PERFORMANCE_NOT_FOUND: 'Không tìm thấy hiệu quả công việc',
  GET_PERFORMANCE_SUCCESS: 'Lấy thông tin hiệu quả công việc thành công',
  GET_LIST_PERFORMANCE_SUCCESS: 'Lấy danh sách hiệu quả công việc thành công',
  UPDATE_PERFORMANCE_SUCCESS: 'Cập nhật hiệu quả công việc thành công',
  NAME_REVENUE_MUST_BE_STRING: 'Tên hạng mục phải là dạng chuỗi',
  NAME_REVENUE_LENGTH: 'Tên hạng mục có độ dài từ 3 đến 160 ký tự',
  DESCRIPTION_REVENUE_MUST_BE_STRING: 'Diễn giải phải là dạng chuỗi',
  DESCRIPTION_REVENUE_MAX_LENGTH: 'Diễn giải cho phép nhập tối đa 2000 ký tự',
  NAME_REVENUE_IS_REQUIRED: 'Tên hạng mục là bắt buộc',
  DESCRIPTION_REVENUE_IS_REQUIRED: 'Diễn giải là bắt buộc',
  UNIT_CACULATE_REVENUE_IS_REQUIRED: 'Đơn vị tính là bắt buộc',
  UNIT_CACULATE_REVENUE_MUST_BE_STRING: 'Đơn vị tính phải là dạng chuỗi',
  UNIT_CACULATE_REVENUE_MAX_LENGTH: 'Đơn vị tính chỉ cho phép nhập tối đa 255 ký tự',
  TYPE_REVENUE_INVALID: 'Loại chi phí chưa đúng định dạng',
  PRICE_REVENUE_MUST_BE_INT: 'Đơn giá nhập vào phải là số nguyên',
  PRICE_REVENUE_GREATER_THAN_1: 'Đơn giá nhập vào phải luôn là số nguyên dương',
  QUANTITY_MUST_BE_INT: 'Số lượng nhập vào phải là số nguyên',
  QUANTITY_GREATER_THAN_1: 'Số lượng nhập vào phải luôn là số nguyên dương',
  DIRECTION_REVENUE_INVALID: 'Loại chi phí không hợp lệ',
  DIRECTION_REVENUE_IS_REQUIRED: 'Loại chi phí là bắt buộc',
  ID_REVENUE_IS_REQUIRED: 'Id chi phí là bắt buộc',
  REVENUE_NOT_FOUND: 'Không tìm thấy chi phí',
  CREATE_REVENUE_SUCCESS: 'Thêm chi phí thành công',
  UPDATE_REVENUE_SUCCESS: 'Cập nhật chi phí thành công',
  GET_REVENUE_SUCCESS: 'Lấy thông tin chi tiết chi phí thành công',
  NAME_ACTIVITY_MUST_BE_STRING: 'Tiêu đề hiệu quả hoạt động phải là dạng chuỗi',
  NAME_ACTIVITY_IS_REQUIRED: 'Tiêu đề hiệu quả hoạt động là bắt buộc',
  NAME_ACTIVITY_LENGTH: 'Tiêu đề hiệu quả hoạt động có độ dài từ 2 đến 160 ký tự',
  CONTACT_NAME_ACTIVITY_MUST_BE_STRING: 'Tên người liên hệ phải là dạng chuỗi',
  CONTACT_NAME_ACTIVITY_IS_REQUIRED: 'Tên người liên hệ phải là bắt buộc',
  CONTACT_NAME_ACTIVITY_LENGTH: 'Tên người liên hệ có độ dài từ 2 đến 160 ký tự',
  ACTIVITY_STATUS_INVALID: 'Trạng thái hoạt động không hợp lệ',
  ACTIVITY_NOT_FOUND: 'Không tìm thấy hoạt động',
  CREATE_ACTIVITY_SUCCESSS: 'Thêm hoạt động thành công',
  UPDATE_ACTIVITY_SUCCESS: 'Cập nhật hoạt động thành công',
  GET_DETAIL_ACTIVITY_SUCCESS: 'Lấy thông tin hoạt động thành công',
  GET_LIST_ACTIVITY_SUCCESS: 'Lấy danh sách thông tin hoạt động thành công',
  TAX_CODE_IS_EXISTS: 'Mã số thuế đã tồn tại',
  CONSULTANTOR_IDS_IS_REQUIRED: 'Id người tư vấn là bắt buộc',
  CONSULTANTOR_IDS_MUST_BE_ARRAY: 'Id người tư vấn phải là mảng các id',
  CONSULTANTOR_IDS_ITEM_MUST_BE_ARRAY_NUMBER: 'Các phần tử id trong mảng phải là dạng số',
  CCCD_IS_EXISTS: 'CCCD đã tồn tại'
} as const

export default MSG
