const MSG = {
  VALIDATION_ERR: 'Validate error',
  EMAIL_IS_REQUIRED: 'Email là bắt buộc',
  EMAIL_MUST_BE_STRING: 'Email phải là dạng chuỗi ký tự',
  EMAIL_LENGTH: 'Email có độ dài từ 5 đến 160 ký tự',
  EMAIL_INVALID: 'Email chưa đúng định dạng',
  PASSWORD_IS_REQUIRED: 'Mật khẩu là bắt buộc',
  PASSWORD_LENGTH: 'Mật khẩu có độ dài từ 6 đến 160 ký tự',
  PASSWORD_IS_NOT_STRONG: 'Mật khẩu chưa đủ bảo mật',
  EMAIL_OR_PASSWORD_INCORRECT: 'Email hoặc mật khẩu chưa chính xác',
  LOGIN_SUCCESS: 'Đăng nhập tài khoản thành công',
  LOGOUT_SUCCESS: 'Đăng xuất tài khoản thành công',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token là bắt buộc',
  TOKEN_NOT_FOUND: 'Không tìm thấy token',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token là bắt buộc',
  CREATED_USER_SUCCESS: 'Tạo tài khoản thành công',
  VERIFY_USER_INVALID: 'Tài khoản chưa được xác thực',
  NO_PERMISSION_CREATE_USER: 'Không đủ quyền để tạo user',
  EMAIL_ALREADY_EXISTS: 'Email đã tồn tại',
  ID_IS_REQUIRED: 'Id là bắt buộc',
  ID_MUST_BE_NUMBER: 'Id phải là dạng số',
  USER_NOT_FOUND: 'Không tìm thấy user',
  UPDATED_USER_SUCCESS: 'Cập nhật user thành công',
  FULLNAME_MUST_BE_STRING: 'Họ và tên phải là dạng chuỗi',
  NAME_CUSTOMER_MUST_BE_STRING: 'Tên dịch vụ phải là dạng chuỗi',
  FULLNAME_LENGTH: 'Họ và tên có độ dài từ 4 đến 160 ký tự',
  NAME_CUSTOMER_LENGTH: 'Tên dịch vụ có độ dài từ 3 đến 160 ký tự',
  DATE_OF_BIRTH_ISO8601: 'Ngày tháng năm sinh phải là ISO 8601',
  ASSIGN_AT_ISO8601: 'Assign at phải là ISO 8601',
  AVATAR_MUST_BE_STRING: 'Ảnh đại diện phải là dạng chuỗi',
  AVATAR_LENGTH: 'Ảnh đại diện có độ dài từ 6 đến 255 ký tự',
  ATTACHMENT_LENGTH: 'File đính kèm có độ dài từ 6 đến 255 ký tự',
  ADDRESS_MUST_BE_STRING: 'Địa chỉ phải là dạng chuỗi',
  ADDRESS_LENGTH: 'Địa chỉ có độ dài từ 6 đến 160 ký tự',
  PHONE_MUST_BE_STRING: 'Số điện thoại phải là dạng chuỗi',
  PHONE_LENGTH: 'Số điện có độ dài 10 ký tự',
  CODE_MUST_BE_STRING: 'Mã nhân viên phải là dạng chuỗi',
  CODE_LENGTH: 'Mã nhân viên có độ dài 6 ký tự',
  ROLE_INVALID: 'Role chưa đúng định dạng',
  OLD_PASSWORD_INCORRECT: 'Mật khẩu cũ không chính xác',
  CHANGED_PASSWORD_SUCCESSS: 'Thay đổi mật khẩu thành công',
  NOT_FOUND: 'Not Found',
  UPLOAD_AVATAR_SUCCESSFULLY: 'Upload avatar thành công',
  GET_LIST_USER_SUCCESS: 'Lấy danh sách user thành công',
  GET_DETAIL_USER_SUCCESS: 'Lấy user thành công',
  REFRESH_TOKEN_SUCCESS: 'Refresh token thành công',
  USER_VERIFY_STATUS_INVALID: 'Verify status invalid',
  GET_ME_SUCCESS: 'Lấy thông tin profile user thành công',
  CREATED_CUSTOMER_SUCCESS: 'Thêm mới khách hàng thành công',
  CUSTOMER_TYPE_INVALID: 'Type khách hàng không hợp lệ',
  NAME_CUSTOMER_ALREADY_EXISTS: 'Tên khách hàng đã tồn tại',
  CUSTOMER_NOT_FOUND: 'Không tìm thấy khách hàng',
  TAX_CODE_IS_REQUIRED: 'Mã số thuế là bắt buộc',
  TAX_CODE_LENGTH: 'Mã số thuế cho phép tối thiểu 10 và tối đa 13 ký tự',
  WEBSITE_MUST_BE_STRING: 'Website nhập vào phải là dạng chuỗi',
  WEBSITE_LENGTH: 'Website cho phép tối thiểu 1 và tối đa 50 ký tự',
  SURROGATE_MUST_BE_STRING: 'Người đại diện nhập vào phải là dạng chuỗi',
  SURROGATE_MUST_LENGTH: 'Người đại diện nhập vào có độ dài từ 4 đến 160 ký tự',
  ATTACHMENT_MUST_BE_STRING: 'File đính kèm phải là dạng chuỗi',
  NOTE_MAX_LENGTH: 'Ghi chú không được phép vượt quá 2000 ký tự',
  UPDATED_CUSTOMER_SUCCESS: 'Cập nhật thông tin khách hàng thành công',
  IS_CUSTOMER_COMPANY: 'Khách hàng phải là khách hàng doanh nghiệp',
  IS_CUSTOMER_PERSONAL: 'Khách hàng phải là khách hàng cá nhân',
  CUSTOMER_GENDER_INVALID: 'Giới tính khách hàng chưa phù hợp',
  LIMIT_LENGHT: 'Giới hạn phân trang có giá trị phải lớn 1 và bé hơn 100',
  PAGE_INVALID: 'Số trang phải có giá trị lớn hơn 1 hoặc bằng 1',
  UPLOAD_FILE_SUCCESSFULLY: 'Upload file đính kèm thành công',
  CUSTOMER_STATUS_INVALID: 'Trạng thái khách hàng phải là Active hoặc Deactivated',
  CUSTOMER_VERIFY_INVALID: 'Xác thực khách hàng phải là Unverified hoặc Verified',
  GET_LIST_CUSTOMER_SUCCESS: 'Lấy danh sách khách hàng thành công',
  CCCD_IS_REQUIRED: 'Căn cước công dân là bắt buộc',
  CCCD_LENGTH: 'Độ dài căn cước công dân là 12 chuỗi ký tự',
  ATTACHMENTS_IS_REQUIRED: 'Attachments là bắt buộc',
  ATTACHMENTS_MUST_BE_ARRAY: 'Attachments phải là mảng',
  ATTACHMENT_ITEM_MUST_BE_ARRAY_STRING: 'Attachments item phải là dạng chuỗi',
  GET_CUSTOMER_SUCCESS: 'Lấy thông tin khách hàng thành công',
  CUSTOMER_IS_VERIFIED: 'Khách hàng đã được xác thực trước đó',
  RESET_PASSWORD_SUCCESS: 'Làm mới mật khẩu thành công'
} as const

export default MSG
