export const PREFIX_API = '/api'
export const PREFIX_USER = '/user'
export const PREFIX_CUSTOMER = '/customer'
export const PREFIX_PERFORMANCE = '/performance'
export const PREFIX_REVENUE = '/revenue'
export const PREFIX_ACTIVITY = '/activity'
